name: "Windows Build"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4
      - name: Get version
        id: get_version
        run: echo "VERSION=$(node -p "require('./src-tauri/tauri.conf.json').version")" >> $GITHUB_OUTPUT

  build-windows:
    needs: prepare
    runs-on: windows-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      - uses: swatinem/rust-cache@v2
        with:
          workspaces: "src-tauri -> target"
          cache-directories: "~/.cargo/registry/index/,~/.cargo/registry/cache/,~/.cargo/git/db/"
          shared-key: "windows-rust-cache"
          save-if: "true"
      - run: bun install
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --target x86_64-pc-windows-msvc
      - name: Rename Windows Artifact
        shell: pwsh
        run: |
          $bundlePath = "src-tauri/target/x86_64-pc-windows-msvc/release/bundle/msi"
          if (Test-Path $bundlePath) {
            Get-ChildItem -Path "$bundlePath/*.msi" | ForEach-Object {
              $newName = "Qopy-${{ needs.prepare.outputs.version }}_x64.msi"
              Rename-Item -Path $_.FullName -NewName $newName
            }
          } else {
            Write-Error "Path ${bundlePath} does not exist."
            exit 1
          }
      - uses: actions/upload-artifact@v4
        with:
          name: windows-x64
          path: src-tauri/target/x86_64-pc-windows-msvc/release/bundle/msi/*.msi
